# modules/pte/managers/test_pool_manager.py
"""
PTE Test Pool Manager — Shared pool + dynamic growth + per-user progress.

v5.3 — MUTABLEDICT FIX (SQLAlchemy):
  • `get_or_generate()` अब `pool_item.test_data` र `result` लाई `dict()` मा
    convert गरेर return गर्छ। यसले app.py मा `result['_pool_id'] = pool_id`
    गर्दा आउने `Can't flag attribute 'test_data' modified` error हटाउँछ।
  • ६ return statements fix: 4× pool_item.test_data, 2× result dict.

v5.2 — THREAD-SAFE CAP PERSISTENCE (race-condition fix):
  • Added module-level `_CAPS_LOCK` (RLock) so concurrent Flask threads
    can't clobber each other's cap increments.
  • `_bump_cap()`, `set_pool_cap()`, `reset_caps()` now perform an
    atomic read-modify-write under the lock.
  • `_get_cap()` first-time-init path also protected.
  • Multi-process note: threading.RLock only protects within one process.

v5.1 — DYNAMIC POOL SIZING:
  • Each module starts at `initial` size (pre-generated by admin).
  • When a user exhausts ALL pool tests → cap grows by `step` (up to `max`).
  • One fresh test is generated immediately for that exhausted user.

Storage estimates (JSON in DB):
  • pte_reading/listening/speaking_writing: ~50 KB/test
  • pte_full: ~200 KB/test
  • 1000 tests × 50 KB ≈ 50 MB/module (worst case) — negligible.
"""

import logging
import threading
from datetime import datetime, timezone, timedelta
from typing import Dict, Any, Optional, Tuple, Callable, List, Set

from sqlalchemy.exc import IntegrityError

from ..models import (
    db,
    PTETestPool,
    PTEGenerationLock,
    PTEUserPoolProgress,
    PTESetting,
)

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════
# v5.2 — process-wide lock for cap read-modify-write
# ═══════════════════════════════════════════════════════════════════════
_CAPS_LOCK = threading.RLock()


# ═══════════════════════════════════════════════════════════════════════
# DYNAMIC POOL CONFIG
# ═══════════════════════════════════════════════════════════════════════
MODULE_POOL_CONFIG: Dict[str, Dict[str, int]] = {
    'pte_reading': {'initial': 100, 'step': 100, 'max': 1000},
    'pte_listening': {'initial': 100, 'step': 100, 'max': 1000},
    'pte_speaking_writing': {'initial': 100, 'step': 100, 'max': 1000},
    'pte_full': {'initial': 50, 'step': 50, 'max': 500},
}

# ═══════════════════════════════════════════════════════════════════════
# BACKWARD-COMPAT: MAX_POOL_SIZE
# ═══════════════════════════════════════════════════════════════════════
MAX_POOL_SIZE = max(cfg['max'] for cfg in MODULE_POOL_CONFIG.values())  # 1000

# Lock / retry config
LOCK_TIMEOUT_SECONDS = 300  # 5 min — force-release stale locks
RETRY_AFTER_SECONDS = 3     # client retry interval after 202

KNOWN_MODULES = list(MODULE_POOL_CONFIG.keys())

# Key prefix for storing per-module cap in PTESetting
_CAP_KEY_PREFIX = 'pte_pool_cap_'


class PTETestPoolManager:
    """Shared pool + dynamic growth + user progress + single-generator election."""

    # ═════════════════════════════════════════════════════════════════
    # HELPERS — MutableDict → plain dict
    # ═════════════════════════════════════════════════════════════════
    @staticmethod
    def _to_plain_dict(data: Any) -> Optional[Dict]:
        """
        v5.3 — Convert SQLAlchemy MutableDict (or None) to plain dict.

        SQLAlchemy 2.0 stores JSON columns as MutableDict, which raises
        `InvalidRequestError: Can't flag attribute modified` when the
        calling code (e.g. app.py) tries to mutate it after the object
        is detached.  We return a plain `dict` to avoid that.

        Safe for None / non-dict values.
        """
        if data is None:
            return None
        if isinstance(data, dict):
            return dict(data)
        try:
            return dict(data)
        except (TypeError, ValueError):
            return data

    # ═════════════════════════════════════════════════════════════════
    # DYNAMIC CAP — READ / BUMP
    # ═════════════════════════════════════════════════════════════════
    def _get_cap(self, module: str) -> int:
        """
        Return current cap for a module.

        Cap starts at `initial` and grows by `step` when users exhaust it.
        Stored in PTESetting so it survives restarts.

        v5.2 — first-time init path is atomic under _CAPS_LOCK.
        """
        cfg = MODULE_POOL_CONFIG.get(module)
        if not cfg:
            return 0

        key = f"{_CAP_KEY_PREFIX}{module}"

        with _CAPS_LOCK:
            try:
                stored = PTESetting.get_value(key, None)
                if stored is not None:
                    cap = int(stored)
                    return max(cfg['initial'], min(cap, cfg['max']))
            except (ValueError, TypeError) as e:
                logger.warning(f"Invalid stored cap for {module}: {e}")

            # First time — initialize to `initial`
            try:
                PTESetting.set_value(key, str(cfg['initial']))
            except Exception as e:
                logger.warning(f"Could not persist initial cap for {module}: {e}")
            return cfg['initial']

    def _bump_cap(self, module: str) -> Tuple[int, int]:
        """
        Increase the module's cap by `step` (up to `max`).
        Returns (old_cap, new_cap).

        v5.2 — ENTIRE read-modify-write is atomic under _CAPS_LOCK.
        """
        cfg = MODULE_POOL_CONFIG.get(module)
        if not cfg:
            return (0, 0)

        key = f"{_CAP_KEY_PREFIX}{module}"

        with _CAPS_LOCK:
            old_cap = cfg['initial']
            try:
                stored = PTESetting.get_value(key, None)
                if stored is not None:
                    try:
                        old_cap = int(stored)
                    except (ValueError, TypeError):
                        old_cap = cfg['initial']
            except Exception as e:
                logger.warning(f"Could not read cap for {module}: {e}")

            old_cap = max(cfg['initial'], min(old_cap, cfg['max']))

            if old_cap >= cfg['max']:
                try:
                    PTESetting.set_value(key, str(old_cap))
                except Exception:
                    pass
                return (old_cap, old_cap)

            new_cap = min(old_cap + cfg['step'], cfg['max'])
            try:
                PTESetting.set_value(key, str(new_cap))
                logger.info(
                    f" Pool cap bumped for {module}: {old_cap} → {new_cap} "
                    f"(max={cfg['max']})"
                )
            except Exception as e:
                logger.exception(f"Failed to bump cap for {module}: {e}")

            return (old_cap, new_cap)

    def get_pool_cap(self, module: str) -> int:
        """Public helper for admin UI."""
        return self._get_cap(module)

    def set_pool_cap(self, module: str, cap: int) -> bool:
        """Admin override — set explicit cap (bounded by config)."""
        cfg = MODULE_POOL_CONFIG.get(module)
        if not cfg:
            return False
        cap = max(cfg['initial'], min(int(cap), cfg['max']))
        try:
            with _CAPS_LOCK:
                PTESetting.set_value(f"{_CAP_KEY_PREFIX}{module}", str(cap))
            logger.info(f" Pool cap SET for {module}: {cap}")
            return True
        except Exception as e:
            logger.exception(f"set_pool_cap failed for {module}: {e}")
            return False

    # ═════════════════════════════════════════════════════════════════
    # POOL — READ / STATS
    # ═════════════════════════════════════════════════════════════════
    def get_pool_size(self, module: str) -> int:
        try:
            return PTETestPool.query.filter_by(module=module, is_active=True).count()
        except Exception as e:
            logger.exception(f"get_pool_size failed for {module}: {e}")
            return 0

    def is_pool_full(self, module: str) -> bool:
        return self.get_pool_size(module) >= self._get_cap(module)

    def is_pool_at_hard_max(self, module: str) -> bool:
        cfg = MODULE_POOL_CONFIG.get(module)
        if not cfg:
            return True
        return self.get_pool_size(module) >= cfg['max']

    def get_pool_stats(self) -> Dict[str, Dict[str, Any]]:
        stats: Dict[str, Dict[str, Any]] = {}
        for mod in KNOWN_MODULES:
            cfg = MODULE_POOL_CONFIG[mod]
            size = self.get_pool_size(mod)
            cap = self._get_cap(mod)
            stats[mod] = {
                'size': size,
                'cap': cap,
                'initial': cfg['initial'],
                'step': cfg['step'],
                'max': cfg['max'],
                'remaining_to_cap': max(0, cap - size),
                'at_cap': size >= cap,
                'at_max': size >= cfg['max'],
            }
        return stats

    def list_pool_items(self, module: str, limit: int = 20) -> List[Dict[str, Any]]:
        try:
            items = (
                PTETestPool.query
                .filter_by(module=module)
                .order_by(PTETestPool.created_at.desc())
                .limit(limit)
                .all()
            )
            return [
                {
                    'id': it.id,
                    'module': it.module,
                    'difficulty': it.difficulty,
                    'question_count': it.question_count,
                    'usage_count': it.usage_count,
                    'is_active': it.is_active,
                    'created_by': it.created_by,
                    'created_at': it.created_at.isoformat() if it.created_at else None,
                }
                for it in items
            ]
        except Exception as e:
            logger.exception(f"list_pool_items failed: {e}")
            return []

    # ═════════════════════════════════════════════════════════════════
    # USER PROGRESS
    # ═════════════════════════════════════════════════════════════════
    def get_user_completed_pool_ids(self, user_id: int, module: str) -> Set[int]:
        try:
            rows = (
                PTEUserPoolProgress.query
                .filter_by(user_id=user_id, module=module)
                .all()
            )
            return {r.pool_id for r in rows}
        except Exception as e:
            logger.exception(f"get_user_completed_pool_ids failed: {e}")
            return set()

    def get_active_pool_ids(self, module: str) -> Set[int]:
        try:
            rows = (
                PTETestPool.query
                .filter_by(module=module, is_active=True)
                .all()
            )
            return {r.id for r in rows}
        except Exception as e:
            logger.exception(f"get_active_pool_ids failed for {module}: {e}")
            return set()

    def is_user_exhausted(self, user_id: int, module: str) -> bool:
        active = self.get_active_pool_ids(module)
        if not active:
            return False
        completed = self.get_user_completed_pool_ids(user_id, module)
        return active.issubset(completed)

    def record_user_progress(self, user_id: int, module: str, pool_id: int) -> bool:
        if not pool_id:
            return False
        try:
            exists = (
                PTEUserPoolProgress.query
                .filter_by(user_id=user_id, module=module, pool_id=pool_id)
                .first()
            )
            if exists:
                return True
            row = PTEUserPoolProgress(
                user_id=user_id,
                module=module,
                pool_id=pool_id,
            )
            db.session.add(row)
            db.session.commit()
            logger.info(
                f" User progress: user {user_id} completed pool #{pool_id} "
                f"({module})"
            )
            return True
        except IntegrityError:
            db.session.rollback()
            return True
        except Exception as e:
            db.session.rollback()
            logger.exception(f"record_user_progress failed: {e}")
            return False

    def _pick_unseen_for_user(
        self, user_id: int, module: str, difficulty: str
    ) -> Optional[PTETestPool]:
        completed = self.get_user_completed_pool_ids(user_id, module)

        q = PTETestPool.query.filter_by(
            module=module, difficulty=difficulty, is_active=True
        )
        if completed:
            q = q.filter(~PTETestPool.id.in_(completed))
        item = (
            q.order_by(PTETestPool.usage_count.asc(), PTETestPool.created_at.asc())
            .first()
        )
        if item:
            return item

        q2 = PTETestPool.query.filter_by(module=module, is_active=True)
        if completed:
            q2 = q2.filter(~PTETestPool.id.in_(completed))
        return (
            q2.order_by(PTETestPool.usage_count.asc(), PTETestPool.created_at.asc())
            .first()
        )

    # ═════════════════════════════════════════════════════════════════
    # POOL — FALLBACK / INCREMENT / RESET
    # ═════════════════════════════════════════════════════════════════
    def _get_next_from_pool(
        self, module: str, difficulty: str = 'medium'
    ) -> Optional[PTETestPool]:
        item = (
            PTETestPool.query
            .filter_by(module=module, difficulty=difficulty, is_active=True)
            .order_by(PTETestPool.usage_count.asc(), PTETestPool.created_at.asc())
            .first()
        )
        if item:
            return item
        return (
            PTETestPool.query
            .filter_by(module=module, is_active=True)
            .order_by(PTETestPool.usage_count.asc(), PTETestPool.created_at.asc())
            .first()
        )

    def _increment_pool_usage(self, pool_item: PTETestPool) -> None:
        try:
            pool_item.usage_count = (pool_item.usage_count or 0) + 1
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.warning(f"Failed to increment pool usage for #{pool_item.id}: {e}")

    def _reset_usage_counts(self, module: str) -> int:
        try:
            count = (
                PTETestPool.query
                .filter_by(module=module)
                .update({'usage_count': 0})
            )
            db.session.commit()
            logger.info(f" Pool usage reset for module {module} ({count} items)")
            return count
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Failed to reset usage for {module}: {e}")
            return 0

    def _count_questions(self, module: str, test_data: Dict) -> int:
        try:
            if module == 'pte_full':
                sections = test_data.get('sections') or {}
                total = 0
                for sec in sections.values():
                    if isinstance(sec, dict):
                        total += len(sec.get('questions') or [])
                return total
            return len(test_data.get('questions') or [])
        except Exception:
            return 0

    def _save_to_pool(
        self,
        module: str,
        difficulty: str,
        test_data: Dict,
        user_id: int,
    ) -> Optional[PTETestPool]:
        """Persist a freshly generated test into the shared pool."""
        total = self._count_questions(module, test_data)
        try:
            pool_item = PTETestPool(
                module=module,
                difficulty=difficulty,
                test_data=test_data,
                created_by=user_id,
                question_count=total,
                usage_count=0,
                is_active=True,
            )
            db.session.add(pool_item)
            db.session.commit()

            logger.info(
                f" Pool SAVE: {module} #{pool_item.id} "
                f"({total} questions) by user {user_id} "
                f"[pool now {self.get_pool_size(module)}/{self._get_cap(module)}]"
            )
            return pool_item
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Failed to save to pool for {module}: {e}")
            return None

    # ═════════════════════════════════════════════════════════════════
    # LOCK — CLEANUP / ACQUIRE / RELEASE
    # ═════════════════════════════════════════════════════════════════
    def _cleanup_expired_locks(self) -> int:
        """Force-release locks held > LOCK_TIMEOUT_SECONDS."""
        try:
            cutoff = (
                datetime.now(timezone.utc).replace(tzinfo=None)
                - timedelta(seconds=LOCK_TIMEOUT_SECONDS)
            )
            expired = (
                PTEGenerationLock.query
                .filter(
                    PTEGenerationLock.status == 'generating',
                    PTEGenerationLock.locked_at.isnot(None),
                    PTEGenerationLock.locked_at < cutoff,
                )
                .all()
            )
            for lock in expired:
                logger.warning(
                    f" Force-releasing expired lock for {lock.module} "
                    f"(held by user {lock.locked_by} since {lock.locked_at})"
                )
                db.session.delete(lock)
            if expired:
                db.session.commit()
            return len(expired)
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Lock cleanup error: {e}")
            return 0

    def _try_acquire_lock(self, module: str, user_id: int) -> bool:
        self._cleanup_expired_locks()

        try:
            lock = PTEGenerationLock(
                module=module,
                status='generating',
                locked_by=user_id,
                locked_at=datetime.now(timezone.utc).replace(tzinfo=None),
                error=None,
            )
            db.session.add(lock)
            db.session.commit()
            logger.info(f" Lock ACQUIRED for {module} by user {user_id}")
            return True
        except IntegrityError:
            db.session.rollback()
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Unexpected lock insert error for {module}: {e}")
            return False

        try:
            existing = PTEGenerationLock.query.filter_by(module=module).first()
        except Exception as e:
            logger.exception(f"Lock re-query failed for {module}: {e}")
            return False

        if not existing:
            return self._try_acquire_lock(module, user_id)

        status = (existing.status or '').lower()

        if status == 'generating':
            logger.info(
                f" {module} already generating "
                f"(by user {existing.locked_by}) — user {user_id} will wait"
            )
            return False

        if status == 'failed':
            logger.info(
                f" Previous {module} generation failed "
                f"({existing.error or 'no error'}) — user {user_id} retrying"
            )
            try:
                existing.status = 'generating'
                existing.locked_by = user_id
                existing.locked_at = datetime.now(timezone.utc).replace(tzinfo=None)
                existing.error = None
                db.session.commit()
                return True
            except Exception as e:
                db.session.rollback()
                logger.exception(f"Failed to take over failed lock for {module}: {e}")
                return False

        logger.info(f" Cleaning stale '{status}' lock for {module}")
        try:
            db.session.delete(existing)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Failed to delete stale lock for {module}: {e}")
            return False

        return self._try_acquire_lock(module, user_id)

    def _release_lock(
        self, module: str, success: bool, error: Optional[str] = None
    ) -> None:
        try:
            lock = PTEGenerationLock.query.filter_by(module=module).first()
            if not lock:
                return

            if success:
                db.session.delete(lock)
                db.session.commit()
                logger.info(f" Lock RELEASED (success) for {module}")
            else:
                lock.status = 'failed'
                lock.error = (error or 'Unknown error')[:500]
                db.session.commit()
                logger.warning(f" Lock marked FAILED for {module}: {error}")
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Lock release error for {module}: {e}")

    # ═════════════════════════════════════════════════════════════════
    # PUBLIC — MAIN ENTRY POINT
    # ═════════════════════════════════════════════════════════════════
    def get_or_generate(
        self,
        module: str,
        difficulty: str,
        user_id: int,
        generate_fn: Callable[[], Optional[Dict]],
    ) -> Tuple[Optional[Dict], str, Optional[int]]:
        """
        Serve test to user.

        Flow (v5.3 — MutableDict fix):
          1. Serve unseen pool test (fast path).       → dict(test_data)
          2. If user exhausted:
             a. If cap < max → bump cap by `step`.
             b. Generate 1 fresh test NOW (synchronous).
             c. If sync generation fails → reset user progress, serve oldest.
          3. If pool empty (first ever) → generate fresh.

        Returns:
            (test_data, source, pool_id)
              source ∈ {'pool', 'generated', 'waiting', 'exhausted', 'failed'}
        """
        if module not in KNOWN_MODULES:
            logger.error(f"Unknown module requested: {module}")
            return None, 'failed', None

        user_exhausted = self.is_user_exhausted(user_id, module)
        pool_size = self.get_pool_size(module)
        current_cap = self._get_cap(module)

        # ─── 1. Serve unseen pool test (fast path) ─────────────────
        if not user_exhausted:
            pool_item = self._pick_unseen_for_user(user_id, module, difficulty)
            if pool_item:
                self._increment_pool_usage(pool_item)
                logger.info(
                    f" UNSEEN SERVE: user {user_id} → {module} #{pool_item.id} "
                    f"(usage now {pool_item.usage_count}, pool {pool_size}/{current_cap})"
                )
                # v5.3 — plain dict
                return self._to_plain_dict(pool_item.test_data), 'pool', pool_item.id

            logger.info(
                f" No unseen pool test for user {user_id} in {module} — "
                f"will generate (pool {pool_size}/{current_cap})"
            )

        # ─── 2. User exhausted OR pool empty ───────────────────────
        if user_exhausted:
            old_cap, new_cap = self._bump_cap(module)
            if new_cap > old_cap:
                logger.info(
                    f" Cap bumped for {module}: {old_cap} → {new_cap} "
                    f"(user {user_id} triggered growth)"
                )
            else:
                logger.info(
                    f" Cap already at max for {module} ({new_cap}) — "
                    f"will reset user {user_id} progress and recycle"
                )

        # ─── 3. GENERATE 1 FRESH TEST ──────────────────────────────
        if self.is_pool_at_hard_max(module) and user_exhausted:
            logger.info(
                f" Pool at hard max for {module} ({pool_size}) — "
                f"resetting user {user_id} progress and re-serving"
            )
            self.reset_user_progress(user_id=user_id, module=module)
            self._reset_usage_counts(module)
            pool_item = self._get_next_from_pool(module, difficulty)
            if pool_item:
                self._increment_pool_usage(pool_item)
                # v5.3 — plain dict
                return self._to_plain_dict(pool_item.test_data), 'pool', pool_item.id
            return None, 'exhausted', None

        if not self._try_acquire_lock(module, user_id):
            return None, 'waiting', None

        try:
            reason = 'exhausted' if user_exhausted else 'empty-pool'
            logger.info(
                f" GENERATING {module} (user {user_id}, reason={reason}, "
                f"pool {pool_size}/{current_cap})"
            )
            result = generate_fn()

            if not result:
                raise ValueError("generate_fn returned None")
            if not isinstance(result, dict):
                raise ValueError(f"generate_fn returned non-dict: {type(result)}")

            success_flag = result.get('success', True)
            has_payload = bool(result.get('questions') or result.get('sections'))

            if success_flag and has_payload:
                pool_item = self._save_to_pool(module, difficulty, result, user_id)
                self._release_lock(module, success=True)

                if pool_item:
                    # v5.3 — plain dict
                    return self._to_plain_dict(result), 'generated', pool_item.id

                logger.warning(
                    f" Pool save failed for {module} — serving without pool_id"
                )
                # v5.3 — plain dict
                return self._to_plain_dict(result), 'generated', None

            error_msg = result.get('error') or 'Generation returned empty payload'
            logger.error(f" Generation failed for {module}: {error_msg}")
            self._release_lock(module, success=False, error=str(error_msg))

            if user_exhausted:
                logger.info(
                    f"↩ Fallback: resetting user {user_id} and serving from pool"
                )
                self.reset_user_progress(user_id=user_id, module=module)
                pool_item = self._get_next_from_pool(module, difficulty)
                if pool_item:
                    self._increment_pool_usage(pool_item)
                    # v5.3 — plain dict
                    return self._to_plain_dict(pool_item.test_data), 'pool', pool_item.id

            return None, 'failed', None

        except Exception as e:
            logger.exception(f"Generation exception for {module}: {e}")
            self._release_lock(module, success=False, error=str(e))

            if user_exhausted:
                self.reset_user_progress(user_id=user_id, module=module)
                pool_item = self._get_next_from_pool(module, difficulty)
                if pool_item:
                    self._increment_pool_usage(pool_item)
                    # v5.3 — plain dict
                    return self._to_plain_dict(pool_item.test_data), 'pool', pool_item.id

            return None, 'failed', None

    # ═════════════════════════════════════════════════════════════════
    # ADMIN — RESET / STATS
    # ═════════════════════════════════════════════════════════════════
    def reset_pool(self, module: Optional[str] = None) -> int:
        try:
            q = PTETestPool.query
            if module:
                q = q.filter_by(module=module)
            count = q.delete(synchronize_session=False)
            db.session.commit()
            logger.info(f" Pool reset: deleted {count} items ({module or 'all'})")
            return count
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Pool reset failed: {e}")
            return 0

    def reset_locks(self) -> int:
        try:
            count = PTEGenerationLock.query.delete(synchronize_session=False)
            db.session.commit()
            logger.info(f" Lock table cleared ({count} rows)")
            return count
        except Exception as e:
            db.session.rollback()
            logger.exception(f"Lock reset failed: {e}")
            return 0

    def reset_user_progress(
        self, user_id: Optional[int] = None, module: Optional[str] = None
    ) -> int:
        try:
            q = PTEUserPoolProgress.query
            if user_id is not None:
                q = q.filter_by(user_id=user_id)
            if module:
                q = q.filter_by(module=module)
            count = q.delete(synchronize_session=False)
            db.session.commit()
            logger.info(
                f" User progress reset ({count} rows, user={user_id or 'all'}, "
                f"module={module or 'all'})"
            )
            return count
        except Exception as e:
            db.session.rollback()
            logger.exception(f"User progress reset failed: {e}")
            return 0

    def reset_all(self) -> Dict[str, int]:
        """Full reset — pool + locks + user progress. Caps NOT reset."""
        pools_deleted = self.reset_pool(None)
        locks_deleted = self.reset_locks()
        progress_deleted = self.reset_user_progress()
        return {
            'pool_items_deleted': pools_deleted,
            'locks_deleted': locks_deleted,
            'user_progress_deleted': progress_deleted,
        }

    def reset_caps(self) -> Dict[str, int]:
        """Reset all module caps back to their `initial` values."""
        result = {}
        with _CAPS_LOCK:
            for mod, cfg in MODULE_POOL_CONFIG.items():
                try:
                    PTESetting.set_value(f"{_CAP_KEY_PREFIX}{mod}", str(cfg['initial']))
                    result[mod] = cfg['initial']
                    logger.info(f" Cap reset for {mod}: → {cfg['initial']}")
                except Exception as e:
                    logger.exception(f"Cap reset failed for {mod}: {e}")
                    result[mod] = -1
        return result


# ═══════════════════════════════════════════════════════════════════════
# SINGLETON
# ═══════════════════════════════════════════════════════════════════════
pte_test_pool_manager = PTETestPoolManager()


__all__ = [
    'PTETestPoolManager',
    'pte_test_pool_manager',
    'MODULE_POOL_CONFIG',
    'KNOWN_MODULES',
    'RETRY_AFTER_SECONDS',
    'MAX_POOL_SIZE',
]